// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function GenerateReport(arg1:app.GenerateRequest):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
