// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateReport(arg1) {
  return window['go']['app']['ImageReportApp']['GenerateReport'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['ImageReportApp']['Startup'](arg1);
}
